title:             An Phạm
email:             an.pham@fake.mail
description:       Tổng hợp những suy nghĩ và kiến thức hữu ích mà mình muốn chia sẻ với mọi người
author:            An Phạm
avatar:            https://avatars2.githubusercontent.com/u/2342885?s=460&v=4
baseurl:           ""
url:               "https://anpham.dev"

# Social Profiles
twitter_username:  
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate


