title:             Dev Note
email:             an.pham@fake.mail
description:       I am the Kira of Dev Note looking to spread the knowledge...
author:            An Phạm
avatar:            https://avatars2.githubusercontent.com/u/2342885?s=460&v=4
baseurl:           ""
url:               "https://anpham.dev"

# Social Profiles
twitter_username:  
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate


